export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const RETRIEVE_ACCOUNTS = "RETRIEVE_ACCOUNTS";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//filters

export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const SORT_BY_RATING = "SORT_BY_RATING";
